/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mainmaintyperacer;

/**
 *
 * @author saloni
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    int a;
    String username;
    public HomePage()
    {
       initComponents();
    }
    public HomePage(String user) {
        username=user;
         a=(int)(Math.random()*10);
            
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        single = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        host = new javax.swing.JButton();
        records = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        single.setText("SINGLE PLAYER");
        single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleActionPerformed(evt);
            }
        });
        getContentPane().add(single);
        single.setBounds(180, 50, 107, 23);

        multi.setText("MULTIPLAYER");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        getContentPane().add(multi);
        multi.setBounds(180, 100, 107, 23);

        host.setText("HOST");
        host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostActionPerformed(evt);
            }
        });
        getContentPane().add(host);
        host.setBounds(180, 160, 100, 23);

        records.setText("HIGH SCORES");
        records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordsActionPerformed(evt);
            }
        });
        getContentPane().add(records);
        records.setBounds(180, 230, 101, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jack-kerouac-typewriter.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -6, 530, 360);

        setSize(new java.awt.Dimension(539, 393));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void singleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleActionPerformed
        // TODO add your handling code here:
        Gameframe obj=new Gameframe(username);
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_singleActionPerformed

    private void hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //int a=(int)(Math.random()*10);
            
        clientmainserver ob=new clientmainserver(username,a);
        ob.setVisible(true);
//        StartMulti ob=new StartMulti();
       server1 obj=new server1();
       Thread X= new Thread(obj);
       X.start();
        
       // host.setEnabled(false);
        //obj.setVisible(true);
    }//GEN-LAST:event_hostActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        // TODO add your handling code here:
        clientmain obj1=new clientmain(username,a);
        System.out.println("hello2"+username);
        obj1.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_multiActionPerformed

    private void recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordsActionPerformed
        // TODO add your handling code here:
        singlescore obj = new singlescore();
        obj.setVisible(true);
    }//GEN-LAST:event_recordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton host;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton multi;
    private javax.swing.JButton records;
    private javax.swing.JButton single;
    // End of variables declaration//GEN-END:variables
}
